= Link Verifier

This is a simple tool intended to help identify broken links created when migrating from one static site
generator (SSG) to another. It was born from the effort to migrate various https://wildfly.org[WildFly] sites from https://jekyllrb.com/[Jekyll] to https://iamroq.com[Roq].

It's very simple: it crawls one site, building a list of internal links, attempts to massage those links to match your local development site, then verifies that link works. If it doesn't, it prints a message. Once you have that list, it will be up to you to clean up any valid broken links.

== Building

Building the tool is very simple:

[source]
----
$ mvn package
----

Once built, you can run the tool using `target/link-verifier.jar`.

== Usage

There are only a handful of commandline options:

-----
$ java -jar target/link-verifier.jar -h
Usage: link-verifier [-chw] [-f=<linkFile>] [-l=<local>] [-r=<remote>]
                     [-a=<aliases>]... [-i=<ignore>]...
Validates that links generated on a remote site are resolvable on the local dev
site.
  -a, --alias=<aliases>   An alias the site may use (e.g., https://www.example.
                            com -> https://example.com)
  -c, --check, --verify   Whether to verify a remote URL before verifying
                            locally. This avoids false positives from broken
                            links on the remote site.
  -f, --link-file=<linkFile>
                          A file containing links to check
  -h, --help              Display this help message
  -i, --ignore=<ignore>   Paths to ignore. Can be repeated for multiple paths.
  -l, --local=<local>     The local site to check
  -r, --remote=<remote>   The remote site to crawl
  -w, --walk              Whether to walk the remote site. Once the site is
                            walked, --link-file can be used to avoid excessive
                            traffic.
-----

To crawl the remote site, you _must_ specify `-w`. This off-by-default option allows us to run the tool to crawl the remote site once, then run it repeatedly to use the generated list of links to verify our local site without causing excessive traffic to the production site. It's probably a premature optimization, but it seemed prudent. 8-)

== Example

-----
$ java -jar target/link-verifier.jar \
    -w \
    --verify \
    --remote https://www.wildfly.org \
    --alias https://wildfly.org \
    --local http://localhost:8080 \
    --link-file wildfly.org.txt
...
The URL https://www.wildfly.org/assets/css/main.css from the original site was not found in the local site: http://localhost:8080/assets/css/main.css
Found 472 good links and 1 invalid links.
-----

== Feedback Welcome

This is a pretty quick-and-dirty tool I cobbled together, but perhaps it will help someone else. If you do find it useful, but need some changes, please feel free to file a pull request and we can talk it over.

Enjoy!
